In [4]:
import itertools
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from collections import OrderedDict
import h5py
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.models import load_model
import warnings
warnings.filterwarnings('ignore')

Using TensorFlow backend.


In [5]:
# Paths to data features and test song features:

TRAIN = '../Features/dataset_features/data_features.csv'
TEST = '../Features/test_songs_features/test_features.csv'
TEST_SPLIT = '../Features/test_songs_features/test_features_split.csv'
MODEL = 'FC_NN.h5'

In [6]:
# load model
model = load_model('FC_NN.h5')
# summarize model.
model.summary()


W0807 18:00:08.439169 140287659005760 deprecation_wrapper.py:119] From /home/maximiliano/miniconda3/envs/music/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0807 18:00:08.469296 140287659005760 deprecation_wrapper.py:119] From /home/maximiliano/miniconda3/envs/music/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0807 18:00:08.497174 140287659005760 deprecation_wrapper.py:119] From /home/maximiliano/miniconda3/envs/music/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:131: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0807 18:00:08.498379 140287659005760 deprecation_wrapper.py:119] From /home/maximiliano/miniconda3/envs/music/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:133: The name tf.plac

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_37 (Dense)             (None, 256)               19968     
_________________________________________________________________
dropout_28 (Dropout)         (None, 256)               0         
_________________________________________________________________
dense_38 (Dense)             (None, 128)               32896     
_________________________________________________________________
dropout_29 (Dropout)         (None, 128)               0         
_________________________________________________________________
dense_39 (Dense)             (None, 64)                8256      
_________________________________________________________________
dropout_30 (Dropout)         (None, 64)                0         
_________________________________________________________________
dense_40 (Dense)             (None, 10)                650       
Total para

In [14]:
def normalize(path):
    """
    Normalize test data for prediction
    """
    # Training data:
    data = pd.read_csv(TRAIN)
    X = data.drop('genre', axis=1)
    # Test data:
    tdata = pd.read_csv(path)
    Xt = tdata.drop('genre', axis=1)
    yt = tdata.genre
    rows = Xt.shape[0]
    # Append original data and test data for normalization:
    Xt = X.append(Xt, ignore_index=True)
    # Normalize:
    sc = StandardScaler().fit_transform(Xt.values)
    Xt = pd.DataFrame(sc[-rows:], index=Xt[-rows:].index, columns=Xt.columns)
    splits = int(rows/10)
    return Xt, yt, splits

In [15]:
X, y, sp = normalize(TEST)

In [16]:
sp

1

In [17]:
X, y, sp = normalize(TEST_SPLIT)

In [20]:
sp

3

In [100]:
#cargo csvs:
data=pd.read_csv("../Features/features_augmented.csv")#training data
t1data=pd.read_csv("../Features/features_augmented_t1.csv")#test songs 1 row
t3data=pd.read_csv("../Features/features_augmented_t3.csv")#test songs 3 rows

In [101]:
X=data.drop('genre',axis=1)
Xt1=t1data.drop('genre',axis=1)
Xt3=t3data.drop('genre',axis=1)

In [102]:
yt1=t1data.genre
yt3=t3data.genre
X.shape

(8910, 77)

In [103]:
Xt1=X.append(Xt1,ignore_index=True)
Xt3=X.append(Xt3,ignore_index=True)

In [104]:

sc1=StandardScaler().fit_transform(Xt1.values)
sc3=StandardScaler().fit_transform(Xt3.values)

Xt1=pd.DataFrame(sc1[-10:], index=Xt1[-10:].index, columns=Xt1.columns)
Xt3=pd.DataFrame(sc3[-30:], index=Xt3[-30:].index, columns=Xt3.columns)

In [105]:
test_loss, test_acc = model.evaluate(Xt1,yt1)
print(test_loss, test_acc)

10/10 [==============================] - 0s 27ms/step
0.5942081212997437 0.800000011920929


In [72]:
model.predict_classes(Xt1)

array([5, 1, 2, 3, 4, 5, 6, 7, 9, 9])

In [106]:
test_loss, test_acc = model.evaluate(Xt3,yt3)
print(test_loss, test_acc)

30/30 [==============================] - 0s 423us/step
0.9436196088790894 0.8333333134651184


In [81]:
genres = {'blues': 0, 'classical': 1, 'country': 2, 'disco': 3, 'hiphop': 4, 
          'jazz': 5, 'metal': 6, 'pop': 7, 'reggae': 8, 'rock': 9}

In [124]:
Xsp1=pd.read_csv("../Features/fsp1.csv")#test songs 1 row
Xsp3=pd.read_csv("../Features/fsp3.csv")#test songs 3 rows
Xsp1=X.append(Xsp1,ignore_index=True)
Xsp3=X.append(Xsp3,ignore_index=True)

sc1=StandardScaler().fit_transform(Xsp1.values)
sc3=StandardScaler().fit_transform(Xsp3.values)


Xsp1=pd.DataFrame(sc1[-1:], index=Xt1[-1:].index, columns=Xt1.columns)
Xsp3=pd.DataFrame(sc3[-3:], index=Xt3[-3:].index, columns=Xt3.columns)




In [125]:
model.predict_classes(Xsp1)

array([8])

In [126]:
model.predict(Xsp1)

array([[4.4347332e-03, 1.5072101e-04, 8.9566214e-03, 8.1167752e-03,
        2.9062687e-03, 1.1398055e-04, 4.0776687e-04, 1.1468789e-02,
        9.4445282e-01, 1.8991562e-02]], dtype=float32)

In [127]:
model.predict_classes(Xsp3)

array([8, 8, 8])

In [91]:
model.predict(Xsp1)

array([[3.5550096e-03, 8.0931502e-05, 1.1809486e-02, 8.3717680e-01,
        1.1275105e-01, 1.6493093e-03, 7.2042859e-04, 9.0997173e-03,
        2.0600369e-02, 2.5568816e-03]], dtype=float32)

In [87]:
model.predict(Xsp1)

array([[4.0721011e-04, 5.1566737e-04, 4.7162161e-04, 1.3951976e-04,
        2.6522547e-02, 1.1368097e-04, 9.5937091e-01, 3.0514673e-05,
        7.4185315e-04, 1.1686442e-02]], dtype=float32)